spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/student-management-system
    username: postgres
    password: pelon

  jpa:
    hibernate:
      ddl-auto: create-drop

server:
  servlet:
    session:
      persistent: false